### ISSUE TITLE
BUGProblem with AGC and s-meter

### ISSUE THREAD

**Issue by Amenra78** [kamilsss655/uv-k5-firmware-custom#104]
Hello, instead of adding some pointless additions and functions such as Messenger and other inventions, it would be useful to finally tidy things up and repair the AGC and s-meter readings. At the moment, its indications are far from the truth and the radio itself is half deaf. Additionally, after AGC calibration, the changes do not want to be saved. I recommend dealing with this first. Regards.

**Comment by kamilsss655** [comment]
This firmware doesn't have AGC calibration.
It is not half deaf and the s-meter readings are correct.

Messenger and other inventions are not half as pointless as your problem.
