### ISSUE TITLE
Kein DTMF mehr auf Tasten beim senden.

### ISSUE THREAD

**Issue by MrHoerby** [kamilsss655/uv-k5-firmware-custom#107]
Kein DTMF mehr auf Tasten beim senden.
Ist das aus Platzgründen so gewollt?

**Comment by kamilsss655** [comment]
1. This is an invalid issue.
2. DTMF codes work.

**Comment by MrHoerby** [comment]
Und der 1750Hz Ton auf der F2 Taste bei gedrückter PTT geht auch nicht richtig. Das Gerät fängt dann an zu scannen oder macht sonstigen Unsinn.
Und DTMF geht nur noch über *Scan-Taste.
