### ISSUE TITLE
[BUG] Kein DTMF mehr auf Tasten beim senden.

### ISSUE THREAD

**Issue by MrHoerby** [kamilsss655/uv-k5-firmware-custom#110]
Kein DTMF mehr auf Tasten bei gedrückter PTT.
Ist das aus Platzgründen so gewollt?
DTMF geht nur noch über *Scan-Taste.

Und der 1750Hz Ton auf der F2 Taste bei gedrückter PTT geht auch nicht richtig. Das Gerät fängt dann an zu scannen oder macht sonstigen Unsinn.

**Comment by kamilsss655** [comment]
Invalid issue.
