### ISSUE TITLE
[BUG] When connected to a repeater, the morse code beep enables the messenger read reciept tx.

### ISSUE THREAD

**Issue by IvanMaestroGTR** [kamilsss655/uv-k5-firmware-custom#111]
Whenever the nearest repeater transmits the id morse code the uvk5 misread the signal as message and tx read reciept.

To replicate:
Find yourself a local repeater that the most nearest to you that has morse id.
Press ptt
Listen to the sound, the messenger will activate

Supposed actions:
The messenger should have ignored this signal 

Suggestions:
I suppose is it possible to disable messenger in some channel?

**Comment by kamilsss655** [comment]
Confirmed. Possible improvement is on the roadmap.

**Comment by IvanMaestroGTR** [comment]
Oh btw I noticed when you send messages, there will be a short period of time where the mic is activated

Is it possible to make it muted?  Or maybe insert a universal code (for every k5 with this mod), so that the messenger will not be activated too easily?

**Comment by T1MOXA** [comment]
> The mic activation has been reported here: #68 and should be fixed in v.20. Can you re-check?

Yes, I noticed this problem in v.20 too

**Comment by kamilsss655** [comment]
Confirmed as well. I have re-opened the #68.

**Comment by IvanMaestroGTR** [comment]
From my s meter it shows +10, -98 db
