### ISSUE TITLE
[BUG] Backlight switched to high if u scroll down through settings

### ISSUE THREAD

**Issue by mysugarape** [kamilsss655/uv-k5-firmware-custom#114]
Only a visual bug nothing important, i only like to let u know :)

Description:
Backlight switched back to high, if u set the min backlight (BLMin - 35.50 - for. ex 7) in menu. If u then scroll down again in the settings the backlight switched to 10, if u pass BLMin, BLMAX and it switched back if u passed BltTRX (38.50).

1. Go to Settings -> BLMin -> set value for ex. 7 -> save
2. Exit Settings
3. Open up Settings again, scroll down to BLMin
4. if u scroll over the settings (BLMin) down to (bltTRX)
5. Backlight switched to 10 and switched back to ex. 7 if u passed bltTRX

**Details:**
Firmware version: 20.1

**Additional context**
nothing important only a visual thing ... or maybe it working as expected ... how ever i like to let u know

cheers

**Comment by IvanMaestroGTR** [comment]
Pretty much applies to egzumer firmware too
Whenever you set it below 10, it will still go with highest brightness when you scroll through brightness settings.
