### ISSUE TITLE
[BUG] Extended VFO shows a full bar even the signal is very faint

### ISSUE THREAD

**Issue by Xygen** [kamilsss655/uv-k5-firmware-custom#115]
**Describe the bug**
When entering Extended VFO from channel spectrum a very faint signal is already showing a full bar.

**Expected behavior**
I'd expect a bar which is filled according to it's dBm value.

**Pictures/video**
<img width="851" alt="Screenshot 2024-01-31 085650" src="https://github.com/kamilsss655/uv-k5-firmware-custom/assets/4473704/ae5a7735-287d-4b97-974f-8a9e0915f108">

**Details:**
- Firmware version: 20.1
- Bandwidth: 12.5k
- Power: High
- RxAGC: Fast
- Gain settings (LNAs/LNA/PGA): 3/5/6
- other:

**Additional context**
I can't reproduce this right now, but Kamil asked me to file an issue including the picture.

**Comment by Xygen** [comment]
https://github.com/kamilsss655/uv-k5-firmware-custom/assets/4473704/7dabca71-e15b-490c-9dd0-ffd183748b4d

Here's the video for this issue

**Comment by Xygen** [comment]
More info on the version where this issue has been introduced: With v19.10 this bug did not exist. It seems to be introduced with v20

**Comment by kamilsss655** [comment]
Closing this one, @Xygen let me know if you manage to reproduce it reliably and provide the steps needed to reproduce it.
