### ISSUE TITLE
[BUG] While Rx from local repeater Squelch turns on and off repeatedly

### ISSUE THREAD

**Issue by LackedSky354** [kamilsss655/uv-k5-firmware-custom#129]
**Describe the bug**
While receiving trasmissions from a local repeater Squelch turns on and off repeatedly, turning on the monitor funcion via the press of a side button allows the user to hear the incoming transmission clearly. (Issue has only been present on one repeater, other users report no issue with it whatsoever)

**To Reproduce**
1. Go to channel mode and tune up to a certain repeater in the area (haven't been able to try this while listening from VFO or Spectrum mode)
2. While squelch is turning on and off open it via the monitor function to hear the transmission as intended

**Expected behavior**
Squelch should remain open during the entire time that the radio receives a transmission.

**Pictures/video**

https://streamable.com/gos3sy

https://streamable.com/e6mw50

**Details:**
- Firmware version: 20.5 (Also present on fw v.20.4)
- Bandwidth: 12.5 and 25
- Power: Any
- RxAGC: Tried off, slow and fast
- Gain settings (LNAs/LNA/PGA): Default
- other: When Rx ends a DTMF code is shown on screen.
- Squelch: 1
- MsgEnc: Off
- MsgRx: Off
- MsgAck: Off
- MsgMod: Off
**Additional context**
English is not my main language, so i apologize if this report is at some point hard to understand.

**Comment by kamilsss655** [comment]
Hey, that's interesting indeed. I'd suggest to try downgrading further to like `v.19.5` to rule out any recent bugs.

If that doesn't help then it is likely hardware/conditions related. The squelch off delay is 15ms which is max the radio chip allows. It might be that your conditions, location, antenna cause the squelch to turn off. If that's the case then I'd suggest to adjust these variables and check results.

More expensive radios allow for greater squelch off delay which would probably solve the issue you're having.
