### ISSUE TITLE
[BUG] Messenger ACK not sent on secondary frequencies [A/B]

### ISSUE THREAD

**Issue by tonurics** [kamilsss655/uv-k5-firmware-custom#133]
Settings:
- RxMode = MAIN TX DUAL RX
- MsgAck = True

Firmware 20.5: when receiving a message on the secondary frequency [B] an ACK is not sent back to the sender.

I suspect the ACK is being sent out on the primary frequency [A]. But I have not confirmed this.

**Comment by kamilsss655** [comment]
Well of course it responds on the main frequency, because that's what `MAIN TX DUAL RX` is supposed to do.
If you switch to `DUAL RX RESPOND` it will ACK on the right frequency. :)

**Comment by tonurics** [comment]
Yes, I understand that would work...

But since the ACK is automatic: I was hoping it would behave like DTMF REPLAY. Where a DTMF is sent back to the caller; regardless of RxMode. (At least that has been my experience.)
