### ISSUE TITLE
On AM after strong signal AGC stop working and Smeter left full

### ISSUE THREAD

**Issue by 73-de-LZ** [kamilsss655/uv-k5-firmware-custom#141]
**BEFORE YOU CREATE A BUG REPORT MAKE SURE YOU READ THIS**:
https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/80-%E2%80%90-Tips-&-Tricks-and-Known-Issues

**Describe the bug**
On AM mode, after receiving strong signal S meter stay full.
AGC doesn't recover untill frequency is changed.
**To Reproduce**
1. AM RX strong signal

**Comment by kamilsss655** [comment]
Invalid issue. Please use a template.
