### ISSUE TITLE
[BUG] Radio cannot RX after 2 minutes idle with battery saver and NOAA enabled

### ISSUE THREAD

**Issue by dchauran** [kamilsss655/uv-k5-firmware-custom#146]
**Describe the bug**
When NOAA is enabled in firmware, and battery saver is turned on the radio will stop receiving after about 2 minutes.

**To Reproduce**
- Set ENABLE_NOAA := 1 in makefile, build, flash to radio.
- Enable battery saver in the radio settings menu (default, 80%).
- Wait about 2 minutes (I use the backlight timeout of 2 minutes as a time, but it is NOT tied to backlight timeout as turning it off at 5 seconds it still takes about 2 minutes to stop receiving)
- Transmit from another radio tuned to the same frequency
- No RX
- Press any key on the receiving radio, and it will RX again for 2 minutes.

**Expected behavior**
Radio should receive :)

**Details:**
- Firmware version: Latest main
- Bandwidth: 12.5k
- NOAA-S: on or off
- BatSav: 80%

**Comment by kamilsss655** [comment]
`ENABLE_NOAA` is unsupported and likely should be removed.

Would you be willing to post a PR removing that flag?

**Comment by dchauran** [comment]
I could do that. I dont't need the alerts and can just put the channels in memory anyway.

**Comment by dchauran** [comment]
See #147

**Comment by a7hybnj2** [comment]
Hey,

I just compiled NOAA back into my firmware.

Is there a way to set the 1050 Hz tone when saving the NOAA channel to the radio? I don't want to constantly listen to the weather, but I need the emergency alerts to activate. Any guidance on configuring this would be greatly appreciated!

Thanks!
