### ISSUE TITLE
[BUG] Long-Press-7 (VOX) gives ScanRng & F-NOAA gives NO action

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/uv-k5-firmware-custom#159]
In release 21.1 VOX is not enabled bij default (disabled via Makefile flag).

F-5 / Long press 5 gives **no action**  as [decribed here](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/30-%E2%80%90-Button-functions#5-noaa)

Long-Press-7 (VOX) now gives **ScanRng**

**Comment by kamilsss655** [comment]
Confirmed. Fixed in main.
Will be available in the upcoming releases.

**Comment by kamilsss655** [comment]
@ErikS-web can you check if this is now resolved with v.21.4 ?

**Comment by ErikS-web** [comment]
You repaired the VOX-function in Channel - AND Frequency mode 👍 

And this works

F-5 / Long press 5 only work as [decribed here](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/30-%E2%80%90-Button-functions#5-noaa) 👍

**Comment by kamilsss655** [comment]
Great, thanks Erik!
