### ISSUE TITLE
can not disable ENABLE_SPECTRUM_CHANNEL_SCAN

### ISSUE THREAD

**Issue by nikant** [kamilsss655/uv-k5-firmware-custom#162]
disabling 
ENABLE_SPECTRUM_CHANNEL_SCAN            := 1

with 0 produces the following compilation error:

> In file included from app/action.c:44:
app/spectrum.h:169:6: error: #elif with no expression
  169 | #elif
      |      ^
app/action.c: In function 'ACTION_RunSpectrum':
app/action.c:264:14: error: #elif with no expression
  264 |         #elif
      |              ^
make: *** [Makefile:467: app/action.o] Error 1

**Comment by IvanMaestroGTR** [comment]
Usually in order to remove this error,
You can remove certain codes that are shown from the error.
As you disable them, some codes that correlate to the disabled function will lose its context, causing this to happen.

**Comment by kamilsss655** [comment]
This flag is currently required.
