### ISSUE TITLE
DTMF indicator is overlapping bandwidth used by transceiver (Bandw in menu) 

### ISSUE THREAD

**Issue by krotoniec** [kamilsss655/uv-k5-firmware-custom#167]
**Describe the bug**
When DTMF decoding is on (D Decd ON), its indicator is overlapping bandwidth used by transceiver (Bandw in menu).

**To Reproduce**
1. Go to 'MENU > 50 (D Decd) and turn it ON'.
2. Go back to the main screen either in frequency or channel mode.
3. See the DTMF indicator is overlapping Bandw value.

**Expected behavior**
I'm open for suggestions, but, maybe instead of using "DTMF" simple "D" would be enough, and this way there's enough room on the screen. Anyway, at the moment doesn't look great.

![image](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/45798336/d65c930d-2406-4301-b747-146d742eaf82)

**Details:**
- Firmware version: NUNU c13a667
- Bandwidth: 8.33k
- Power: H

**Comment by kamilsss655** [comment]
I cannot reproduce this issue.

Also:
* There is no "D Decd" option in this firmware
* c13a667 is not a valid version

Can anyone else confirm or deny this issue?
cc @ErikS-web

**Comment by krotoniec** [comment]
I'm little confused. The last commit from 5 days ago is c13a667. It was compiled using custom Makefile with ENABLE_DTMF_CALLING enabled, that's when it shows in menu. It's set to disabled in your firmware by default.

![image](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/45798336/2fdc0019-2c77-4015-bd74-f8a87a2c2877)

![image](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/45798336/05a75937-7364-4bff-8425-9f35793ac6f7)

It easily reproducible, I tried it on 3 different devices.
And "D Decd" it is there, that's the described DTMF calling feature, enabled with ENABLE_DTMF_CALLING.

**Comment by kamilsss655** [comment]
Ohh that explains it. DTMF is not supported by this firmware, which is stated in the wiki.

**Comment by krotoniec** [comment]
I'm sorry it's not explained in the wiki.  There is a number of contradicting statements regarding DTMF. On one hand you are explaining several of DTMF options in the menu, and then at the end you are stating - "DTMF is not supported". 
It's supported or not?

**Comment by ErikS-web** [comment]
I do have to correct and say you did not read the Wiki/Online manual correctly

![Knipsel](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/148579604/603f91d8-2f70-4a07-8e48-cc56ff4190dc)

The specific DTMF-functions are summarised under section **REMOVED**
