### ISSUE TITLE
Is it possible to scroll through the received messages on the list?

### ISSUE THREAD

**Issue by krotoniec** [kamilsss655/uv-k5-firmware-custom#168]
Hi, 
Thank you for your great work. The messaging with the mesh network is simply brilliant. 
I have a question regarding the messaging, is it possible to scroll the messages on the list? 
From what I see right now, there is only 4 last messages visible, and it seems there is no way to scroll up to the very first one.

**Comment by kamilsss655** [comment]
Yes, scrolling is possible with FN1 FN2 buttons starting with v.21.0
