### ISSUE TITLE
[BUG] Can't Manage Encryption to Work

### ISSUE THREAD

**Issue by kasperaitis** [kamilsss655/uv-k5-firmware-custom#170]
![image0](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/1422212/fcb2cae2-25bf-4366-b369-99e9451fae52)
![image1](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/1422212/ba5dc40a-3d20-4121-a89c-6cfaf5b0aa1b)
![image2](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/1422212/5242792b-491f-42eb-a367-6bf97fa29cf2)

**Comment by kamilsss655** [comment]
Well this is not a valid issue to start with. I don't even know what version you are using.
Channel BW, antenna, distance between radios. All of these things matter.
