### ISSUE TITLE
[FEATURE] Extra explanation on AM fix and differences

### ISSUE THREAD

**Issue by KDMcMullan** [kamilsss655/uv-k5-firmware-custom#174]
Not so much a feature request for the firmware, but I don't fully understand how the AM fix works, nor how it differs from the AM fix on other authors' firmware. It would be great if there was an additional paragraph in there, please. I do enjoy this build. Thank you.

**Comment by kamilsss655** [comment]
Feel free to submit such paragraph here.

**Comment by KDMcMullan** [comment]
Ah! You caught me! I'm afraid I have no idea how either works! If you give me a hint, I could go looking and write it up.
