### ISSUE TITLE
[FEATURE] Extra scan option: Scan List 1 + List 2 without unlisted channels.

### ISSUE THREAD

**Issue by Kingdruoid** [kamilsss655/uv-k5-firmware-custom#176]
It would be nice to have an extra option while scanning that involves channels saved for List 1 and channels saved for List 2 but it should not include channels without a list. 

That way the options for scaning would be four in total:
SList 1
SList 2
SList 1+2
Scan ALL

That option could show up in the upper status bar as a "3".

**Comment by jamie-2bit** [comment]
I was under the impression you can already do this.

**Comment by Kingdruoid** [comment]
As of now there are only 3 options to scan: 1, 2 or * (star means: All memory channels)
My request is to add a fourth option to scan channels form List 1 & 2 together but **EXCLUDE** the channels without a list assigned.
The FW from Matoz (@spm81) gives tou this option and it provides greater flexibility while scanning.
