### ISSUE TITLE
[FEATURE] Please use a title that makes sense

### ISSUE THREAD

**Issue by birmanish** [kamilsss655/uv-k5-firmware-custom#178]
Hello, I recently installed this custom firmware because I just got my new quansheng uv-k5. The problem is: I want to change this firmware, so reinstall the original firmware. I tried with the video wich was given with the files, but it didn't work. Can someone help me?

**Comment by kamilsss655** [comment]
Sorry to hear that. This is not a right place to ask. You can try online forums and groups to find more help.
