### ISSUE TITLE
How to disable Apollo Quindar PTT ID? 

### ISSUE THREAD

**Issue by marianomd** [kamilsss655/uv-k5-firmware-custom#180]
Whenever I press the PTT, a tone is emmited, and when I release it, another tone is emmited.

The PTT ID menu item has been removed from this firmware, but the beeps are being transmitted. Is there any way to disable them?

Thank you!

**Comment by kamilsss655** [comment]
I wish I could help but, you didn't file a valid ticket.
It doesn't even have a version number, so I cannot help unfortunately.

**Comment by marianomd** [comment]
Latest free version (20.5). Thanks anyway.
