### ISSUE TITLE
[BUG] No TX and very low audio level on RX/MONITOR

### ISSUE THREAD

**Issue by hiddenvs** [kamilsss655/uv-k5-firmware-custom#183]
**Describe the bug**
Transmit is disabled after flashing the radio with NUNU v20.5. 
Always I press PTT only message appears "VOLT HIGH - TX DISABLE".

**Details:**
- Firmware version: NUNU v.20.5
- others: F LOCK = DEFAULT + 137-174 400-470 
  (doesn't mather what is set, behavior is the same as described)

Radio is classic UV-K5 with 1600 mAh battery bought on Banggood.
Audio level is very low outside of FM radio or beep tone from keyboard.

**Comment by kamilsss655** [comment]
It is not a bug. Voltage is too high.
You might want to read Wiki on how to calibrate the battery or use a different battery.
