### ISSUE TITLE
reticulum

### ISSUE THREAD

**Issue by fab1an2** [kamilsss655/uv-k5-firmware-custom#184]
Meybe creating a compatibility with https://reticulum.network/

**Comment by kamilsss655** [comment]
It is a cool project, but no.

**Comment by 128element** [comment]
You don't have to do the whole reticulum stack.
Read the interfaces. https://markqvist.github.io/Reticulum/manual/interfaces.html 
specyfy pipe interface. If You can create a way to send and receive data trought usb<->audio cable directly from computer this is all.

Please think about this idea.

**Comment by xi-9** [comment]
> You don't have to do the whole reticulum stack.

nice
Reticulum no need ham licence
