### ISSUE TITLE
[FEATURE] Please, Don't scrap NOAA

### ISSUE THREAD

**Issue by a7hybnj2** [kamilsss655/uv-k5-firmware-custom#188]
I have been reading the bug reports and pull requests and see there is a hint of permanently removing the NOAA functionality. I am just here to say please don't do that, unless there is another/better way to receive "NOAA Alerts(1050Hz tone)" for potential emergency circumstances.

I currently have a custom build where I compiled in NOAA and removed the "Encryption"(to make room). I then set spectrum to long M. So, I have everything I need.

Thanks for making and updating this project it really is pretty slick.

**Comment by kamilsss655** [comment]
Thanks for feedback. Glad you made it work!
