### ISSUE TITLE
[BUG] TX hangs and unit freezes in TX mode on blank messenger msg

### ISSUE THREAD

**Issue by BaskeeDK** [kamilsss655/uv-k5-firmware-custom#191]
**BEFORE YOU CREATE A BUG REPORT MAKE SURE YOU READ THIS**:
https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/80-%E2%80%90-Tips-&-Tricks-and-Known-Issues

**Describe the bug**
When sending multiple messages with the encrypted messenger (own key was used), the messenger freezes in TX-mode and broadcasts all button pushes, whilst being unable to exit (m-key, tx-key, nothing responds), until unit is powered off.

**To Reproduce**
1. Go to messenger
2. Send messages back / forth
3. Accidentally push "send" (M) on a blank message
4. Unit freezes in TX-mode and needs turn off/on, lose all chat history

**Expected behavior**
Expect not to be able to send blank message.

**Pictures/video**
<may be added later>

**Details:**
- Firmware version: [9aa505e](https://github.com/kamilsss655/uv-k5-firmware-custom/commit/9aa505e9d1e431d82f003a39605594d9a069eb20)
- Bandwidth: 25k
- Power: l/m/h

**Additional context**
Cannot be reproduced without having sent messages first

**Comment by kamilsss655** [comment]
You are not using the latest supported version `21.4`.
At `21.4` I was not able to reproduce this issue.
