### ISSUE TITLE
Jumbled up text????

### ISSUE THREAD

**Issue by Enki-Hoshi** [kamilsss655/uv-k5-firmware-custom#193]
the text that is recieved on both radios come all like this all jumbled up. how do i fix it???

![20240715_180351](https://github.com/user-attachments/assets/4bf53a7e-dd64-4fe8-a913-e644ca7a0fcb)

**Comment by kamilsss655** [comment]
Could be couple of issues:
- not matching `EncKey` between radios
- not matching `MsgEnc` between radios
- other settings not matching between radios
- radios too close
