### ISSUE TITLE
[BUG] DWR Keeps turning on automatically

### ISSUE THREAD

**Issue by WholesomeMeal** [kamilsss655/uv-k5-firmware-custom#195]
Often after a scan, my radio will turn DWR on again. Usually have it set to DW. 

Firmware version: 20.5

UVK5 (8)

**Comment by WholesomeMeal** [comment]
Unfortunately I don't have access to the early releases. I'll be happy to tell you once I have it.

**Comment by WholesomeMeal** [comment]
Became a Patreon member to test this, yes it still happens. Sometimes when I turn my radio on, DWR is enabled. Despite setting it to DW.

Firmware: v21.4
UKV5(8)

**Comment by WholesomeMeal** [comment]
If I scan through one of my lists, press exit (stop the scan), then turn it off - it will turn back on with **DWR enabled every second time.**

**Comment by kamilsss655** [comment]
Ok, re-opening this one. :eyes:

**Comment by kamilsss655** [comment]
Tested multiple times and could not reproduce with v.21.5. Closing this one. Can be re-opened if someone posts some more detailed steps / video of the issue.

**Comment by WholesomeMeal** [comment]
Scan through saved memories, turn off then on. Repeat. 
When you turn the radio on again DWR will be enabled.

I have replicated this on 5 different radios.

v.21.7

**Comment by WholesomeMeal** [comment]
I have a video of the issue but can't post here because the file size is too large.

**Comment by kamilsss655** [comment]
It could be caused by some edge case related to the invalid EEPROM data on your device. That would explain why I could not reproduce it. Can you try factory reset and try to reproduce the issue?

**Comment by WholesomeMeal** [comment]
Just tried the reset function (ALL) in the menu. Scanned through default memories. Issue is still there.

**Comment by reppad** [comment]
Hi,

I’m having the same issue. I can reproduce it consistently and I’ve tested it with several radios, so I don’t think it’s a case of a corrupted EEPROM. However, it might be some kind of conflict with other parameter values, especially if other users aren’t experiencing the same behavior.

Here is the minimal reproduction scenario:
	1.	Set “RxMode” to “Main TX Dual RX” (aka DW)
	2.	Turn the radio off and on
	3.	Start a scan
	4.	Turn the radio off and on again => the DWR mode is back

Step 2 is mandatory—there must be at least one reboot after enabling DW mode for the bug to occur.

Here’s a video showing the behavior.

https://github.com/user-attachments/assets/591ffa62-cae6-4568-a71b-e9efaca9b586

**Comment by kamilsss655** [comment]
Thanks @reppad for more details. I will re-open this issue an try to reproduce.

**Comment by GlydetheSurfer** [comment]
having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.

**Comment by WholesomeMeal** [comment]
@GlydetheSurfer The bug hasn't been fixed yet

**Comment by kamilsss655** [comment]
> having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.

@GlydetheSurfer you’re welcome to try fixing it yourself, it doesn’t cost anything.

**Comment by GlydetheSurfer** [comment]
> > having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.
> 
> [@GlydetheSurfer](https://github.com/GlydetheSurfer) you’re welcome to try fixing it yourself, it doesn’t cost anything.

Its fine, I have my solution. >:)
