### ISSUE TITLE
Add features from losehu firmware?

### ISSUE THREAD

**Issue by OldMateAidos** [kamilsss655/uv-k5-firmware-custom#196]
I absolutely love this firmware I can't live with out the scanning speed , I was wondering if there could be support for the bigger eprom upgrade , boot up image , automatic Doppler shit , and bigger battery support , I tried to implement myself but am to much of a noob ,

**Comment by kamilsss655** [comment]
Glad you like the firmware. Unfortunately the flash size is a limiting factor, and due to this compromise needs to be made.

**Comment by OldMateAidos** [comment]
I am planing on updating my eprom ,
Are you able to give me some advice we're to start porting auto Doppler shift over
