### ISSUE TITLE
[FEATURE] port SI4732-A10 support

### ISSUE THREAD

**Issue by OldMateAidos** [kamilsss655/uv-k5-firmware-custom#197]
Add code from https://github.com/phdlee/uvk5cec/tree/main

To add SI4732-A10 support for full hf 

I realy want to add this mode but all the firmwares are basic and last luster , I don't want to switch your scanner speed is amazing

**Comment by kamilsss655** [comment]
I'm glad you find the scanner speed amazing.

Support for SI4732 is not on the roadmap for this firmware, due to limited flash size.

**Comment by OldMateAidos** [comment]
Could you give me some advice at what files to look at to try port myself
