### ISSUE TITLE
Increase font size in messenger

### ISSUE THREAD

**Issue by JDAWGSINCE** [kamilsss655/uv-k5-firmware-custom#200]
Is there a way to increase font size?  I would imagine it would be somewhere in /workspaces/uv-k5-firmware-custom/ui/messenger.c, but I am incredibly new to this.

Thank you so much!  Awesome firmware!

**Comment by kamilsss655** [comment]
Unfortunately changing the font size would require other architectural changes (max message length etc.) and is not in the scope of this project.

**Comment by JDAWGSINCE** [comment]
Thank you for your response.

Jason
