### ISSUE TITLE
[FEATURE] Use button `0 FM` to switch demodulation

### ISSUE THREAD

**Issue by MicaelJarniac** [kamilsss655/uv-k5-firmware-custom#204]
**Is your feature request related to a problem? Please describe.**
I never use the FM broadcast radio feature, but it's common to want to switch demodulation.

**Describe the solution you'd like**
In my opinion, it'd make more sense for <kbd>0 FM</kbd> to switch demodulation by default, as I believe it's a more common use case, and have the FM broadcast radio feature optional for the side buttons.

**Comment by kamilsss655** [comment]
You can assign 'switch demodulation' function to one of the side buttons.
More info: https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/30-%E2%80%90-Button-functions#custom-button-functions
