### ISSUE TITLE
Menu functions "NOT ALLOWED"

### ISSUE THREAD

**Issue by ifuchs** [kamilsss655/uv-k5-firmware-custom#206]
I decided to try out the Nunu firmware (version 20.5) for the messaging functions and I thought that this firmware was mostly a superset of the Egzumer firmware. However, if I go to menu functions 16 (SCADD 1), 17 (SCADD 2), 19 (CHDELE), 20 (CHNAME) I get "NOT ALLOWED". Also, all of my channel names seem to have been lost when I upgraded the firmware. I also wanted to be able to send messages using a serial connection to the UV-K5 but it appears that is turned off by default and is added by recompiling the firmware. I tried enabling the hidden menu functions but that did not help.

**Comment by kamilsss655** [comment]
This is not a valid issue.
