### ISSUE TITLE
[FEATURE] Disable Reset When Wrong Password

### ISSUE THREAD

**Issue by teknomanyi3** [kamilsss655/uv-k5-firmware-custom#208]
Hi. How can i disable reset EEPROM when i enter 3 times. I am using in the school and my friends try to password. I dont want reset my device. Thanks

**Comment by kamilsss655** [comment]
Hi. Unfortunately the only way to disable the reset is to not use a password. This is not intended to be changed at the moment.

**Comment by teknomanyi3** [comment]
Thanks.

**Comment by teknomanyi3** [comment]
(https://github.com/user-attachments/assets/074da757-6d36-4e14-b8f8-a6c47ed10f51) I disabled the wrong attempt counter. Now it won't reset.
