### ISSUE TITLE
[BUG] CTCSS Rx muted

### ISSUE THREAD

**Issue by dfx12** [kamilsss655/uv-k5-firmware-custom#211]
**Describe the bug**
With CTCSS Tone set,  no audio  on Receive for Tones 94.7-103.5 - Green light flashes indicating receive but no audio through the speaker

Tested on two indentical UV K5(8) both running v20.5

Appears only to be an RX issue - testing to a 3rd Radio (Baofeng uv 17) TX tone appears to be sent correctly as this Radio with 
the same Tone set can receive without issue

Tones above and below this range work

May be related to :

"ENABLE_MESSENGER_FSK_MUTE          := 1       mutes speaker once it detects fsk sync word (might cause unintentional mutes during ctcss rx)"

but I am unable to compile firmware myself with the flag set to 0 to test

**To Reproduce**
1.  Set CTCSS Tone between 94.7-103.5
2. transmit on another device with  tone set to the tone above
3.  Green light on receiving unit with flash but no audio will come through 

**Expected behavior*
Audio to be played through speaker

**Details:**
- Firmware version: 20.5

**Comment by kamilsss655** [comment]
Does the issue exist on v.21.5 ?

**Comment by kamilsss655** [comment]
Cannot replicate on v.21.5 with `97.4Hz` set for rx and tx ctcss.
