### ISSUE TITLE
[FEATURE] Spectrum analyzer at Power-On (extra menu option)

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/uv-k5-firmware-custom#215]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I prefer to use your (memory channel-) `Spectrum analyser`.
Would be nice to have a menu option to enable this at `Power-On`.

**Comment by kamilsss655** [comment]
Likely not going to be implemented as the spectrum is additional application to the main firmware, not the other way around.

**Comment by kamilsss655** [comment]
Could potentially consider having last open application start-up, but that would be a lot of work. Could open some possibilities though in terms of messenger and other apps.
