### ISSUE TITLE
Extend the available functions for Custom buttons

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/uv-k5-firmware-custom#28]
pse add these to the  [Custom button functions](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/30-%E2%80%90-Button-functions#custom-button-functions)

- Bandwidth switch/toggle
- Activate Spectrum analyzer (like F+5)

**Comment by smokoks** [comment]
**spectrum.c** short press F1 to continue scanning, LONG F1 Black list. Approximately:
 case KEY_SIDELONG1:
Blacklist();
 break;
 Thanks!
