### ISSUE TITLE
squelch level 1

### ISSUE THREAD

**Issue by plopezx** [kamilsss655/uv-k5-firmware-custom#30]
For weak signals, even SQL 1 is a little bit hard. I think that SQL level zero is -143dB, SQL level 1 is -125dB and SQL level 2 is -124dB. Maybe an intermediate value between -143dB and -125dB could help for weak signals.
Thank you

**Comment by kamilsss655** [comment]
Yup, I've noticed the need for more sensitive squelch as well. This will be addressed in future releases.
