### ISSUE TITLE
black list

### ISSUE THREAD

**Issue by Atmanvseredeni** [kamilsss655/uv-k5-firmware-custom#33]
how to reset the black list of frequencies in the spectrum?

**Comment by ErikS-web** [comment]
Did you read the [Online manual in the Wiki](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki)

It's mentioned at [**Extra functionality, button-functions**](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/40-%E2%80%90-Spectrum-analyzer#button-functions)

**Comment by Atmanvseredeni** [comment]
> Ви читали [онлайн-посібник у Wiki](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki)
> 
> Це згадується у [**кнопках функцій**](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/40-%E2%80%90-Spectrum-analyzer#button-functions-1)

Thank you !  ) And if you leave the spectrum or turn off the walkie-talkie, will the set blacklist be reset?

**Comment by ErikS-web** [comment]
Since this is a hobby...try it out...
And report your finding here... ;-)

**Comment by Atmanvseredeni** [comment]
> Оскільки це хобі... спробуйте... І повідомте про свою знахідку тут... ;-)

Checked) If you exit the spectrum, it does not reset, if you turn it off and then turn it on, it resets
