### ISSUE TITLE
Low,Mid & High

### ISSUE THREAD

**Issue by spm81** [kamilsss655/uv-k5-firmware-custom#38]
hello kamilsss655,
When I change the power in memory mode, when I do PTT it changes to the power that was recorded... is that really the case? or is it a bug?

Compliments
Matoz

I personally really like your Spectrum with the memory scan... ;)

**Comment by ErikS-web** [comment]
Yep looks like a bug.

If you change the power, it will returns to the original value as soon as you press PTT

**Comment by ErikS-web** [comment]
OK in V.15, V.16, V.16.2.
With 16.3 the bug is caused.

**Comment by OE1MWW** [comment]
change the power and go to Menu 17 and save the cannel again.
This will set and keep the all the settings.

**Comment by ErikS-web** [comment]
Looks like the value is not store into memory.
See also #39

**Comment by ErikS-web** [comment]
Solved !
