### ISSUE TITLE
Battery Callibration lost after power off/on - resets to original value

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/uv-k5-firmware-custom#39]
When adjusting all looks fine,
Buts after power off/own original value is back on screen.

Looks like the value is not store into memory.

Firmware 16.4

**Comment by ErikS-web** [comment]
This issue occures since v0.3.

So no relation with #38

**Comment by kamilsss655** [comment]
What is power calibration?
What are steps to reproduce the issue?
What is the result and what is the expected result?

**Comment by ErikS-web** [comment]
Yes Voltage callibration of accu.

as is under menu 67. `BatCal` - battery calibration, measure the voltage on the back of the radio, and adjust the value in the menu accordingly

**Comment by kamilsss655** [comment]
Fixed in: https://github.com/kamilsss655/uv-k5-firmware-custom/releases/tag/v.16.5

**Comment by ErikS-web** [comment]
3 X checked... 3x OK
