### ISSUE TITLE
Zawieszanie sie spectrum w trybie kanałowym

### ISSUE THREAD

**Issue by zylka5** [kamilsss655/uv-k5-firmware-custom#44]
W trybie kanałowym czyli hiper szybkim skanowaniu kanałów, sprctrum zawiesza się natychmiast po wejściu. Nic nie da się zrobić trzeba wyłączyć radio.

**Comment by kamilsss655** [comment]
Obniż gain na 0 z odłączoną anteną i dopiero podłącz. 
Zwiększaj gain tylko do takiej wartości, przy której nie występuje zawieszanie.
Tak jak pisałem to radio nie jest odporne na mocne sygnały, szczególnie w spectrum gdzie nie chroni go squelch.

**Comment by zylka5** [comment]
Ale gdzie gain jak? 
Dziwne dziś działa od strzała, a w nocy za cholere nie chciało, odrazu zwis ale tylko w trybie skanowania kanałów. Niby nic nie zmieniałem, nie wiem czary? :D

**Comment by ErikS-web** [comment]
Disconnect the antenna and the freezing will stop.
Press M twice
Then reduce the LNA$ and/or LNA parameter.
Connect the antenna again and see if the value can be slightly higher.

**Comment by zylka5** [comment]
No właśnie nie wiem czy bez anteny dao by się wejść jak problem powróci zobaczę.
Znalazłem inny mały błąd: jak odbiera się jakiś sygnał audio w spectrum to po wyjściu z niego dalej świeci się zielona dioda i słychać lekki szum w głośniku, znika to dopiero po zmianie kanału lun częstotliwości na inny.
