### ISSUE TITLE
🗲FLASH WITH A BROWSER🗲 does not work

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/uv-k5-firmware-custom#45]
Today it does not work (_on [all releases](https://github.com/kamilsss655/uv-k5-firmware-custom/releases)_)
Probably a GitHub issue ?!

_Loading file from url: https://github.com/kamilsss655/uv-k5-firmware-custom/releases/download/v.17/firmware.packed.bin_

_**_Error while loading firmware_**, check log above or developer console for detail._

**Workaround**

Download bij hand the [firmware.packed.bin](https://github.com/kamilsss655/uv-k5-firmware-custom/releases/download/v.17/firmware.packed.bin)
and select the file locally on disk
and Flash, with UVTools.

**Comment by kamilsss655** [comment]
CORS issue. Should work now.
