### ISSUE TITLE
The BUG in AM reception?

### ISSUE THREAD

**Issue by chouyu** [kamilsss655/uv-k5-firmware-custom#47]
After removing the AM Fix code, v.17.1 can receive weak AM signals normally. However, the SLOW AGC produces a burst of noise at the beginning of strong signals, indicating insufficient dynamics. There are two issues with FAST AGC: first, low volume; second, it cannot handle extremely strong signals (e.g., signals when an airplane flies overhead), sometimes resulting in a "PUPUPUPU" sound.

**Comment by chouyu** [comment]
And the sound level not normal, some signals very loud, some signals very silent. 
The issue of uneven volume is not as severe and pronounced when using the AM Fix mode.

**Comment by zylka5** [comment]
Jeszcze taki mały błąd jak mamy na VFO skopiowaną cześtotliwość z kanału (F + 1) to po zmianie w menu rodzaju AGC znika skopiowana czestotliwość i wraca "stara".

**Comment by kamilsss655** [comment]
Thanks @chouyu for detailed information. Based on that I've prepared new release 17.2 can you see how that works for you?

**Comment by chouyu** [comment]
Version 17.2 has better performance compared to version 17.1, and most signals are received normally. However, the SLOW AGC produces a burst of noise at the beginning of strong signals, and then the AGC kicks in to adjust the signal. When encountering extremely strong signals, it still clips significantly. In terms of volume, it is still not as stable as in the AM Fix mode.

**Comment by kamilsss655** [comment]
Ok, I got some other positive reports as well. Closing.

**Comment by chouyu** [comment]
It seems that in the SLOW/FAST AGC modes, the gain is higher compared to the AM Fix mode. As a result, even slightly stronger signals may exhibit clipping distortion in the demodulated audio.
