### ISSUE TITLE
 TX Disable  since 16.3

### ISSUE THREAD

**Issue by grayker** [kamilsss655/uv-k5-firmware-custom#48]
Why, starting from firmware 16.3 and up to 17.1, when trying to TX, even a PMR band writes TX DISABLE. Everything works in version 16.2. Perhaps it has something to do with the menu item 10 - RxOffs:? I don't understand why the value 0.00262 Mhz is entered there. I didn't put it there. in new firmware, should this value be =0 ?
I will be very grateful for the answer!

**Comment by ErikS-web** [comment]
Just read the [online manual....](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/20-%E2%80%90-Menu)

and report if you understand.... (or not.)

Than item may be closed.

Tip... read last line... starting with **IMPORTANT:**

**Comment by grayker** [comment]
> Just read the [online manual....](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/20-%E2%80%90-Menu)
> 
> and report if you understand.... (or not.)
> 
> Than item may be closed.
> 
> Tip... read last line... starting with **IMPORTANT:**

Thank you very much, I couldn't understand this point. I entered the value 0 there and it worked, thank you!
