### ISSUE TITLE
Channel spectrum is still scanning previously deleted channels.

### ISSUE THREAD

**Issue by Xygen** [kamilsss655/uv-k5-firmware-custom#49]
A previously deleted channel is still part of the channel spectrum.
Turing the radio off and back on doesn't help.
It's also not helping to remove the channel from the scan list before deleting.

**Comment by ErikS-web** [comment]
How did you delete ?

Or was is Skip ?

**Comment by Xygen** [comment]
No no, not skip! I've deleted the channel via menu item 19 (ChDele).

**Comment by kamilsss655** [comment]
Does the issue persist after reboot?

**Comment by Xygen** [comment]
Yes, turning the radio off and back on doesn't help.

**Comment by kamilsss655** [comment]
Unfortunately was not able to reproduce. Might be some edge case specific to your channel settings.
Can you upload a video and your chirp channel list the issue occurs on?
