### ISSUE TITLE
Switching from channel mode to VFO does not tune to the correct frequency shown

### ISSUE THREAD

**Issue by Xygen** [kamilsss655/uv-k5-firmware-custom#52]
While listening to a transmission in channel mode, and then switching to VFO, the radio does not tune to the frequency shown in VFO mode. Instead one can still hear the transmission of the channel frequency.
One needs to manually change the frequency (like pressing the up and down buttons) to be able to hear the true transmission of the frequency shown in VFO mode.
A reboot doesn't fix the issue.
Firmware version is 17.2
@kamilsss655 I've sent you 2 videos about that bug. But I can upload them here as well, if that's necessary.

**Comment by sparky93a** [comment]
confirmed here also. sometimes it selected vfo once chn tx ended.

**Comment by zylka5** [comment]
The same situation is after exiting spectrum mode.

**Comment by xes** [comment]
Maybe this is related also with some weird behavior of spectrum view.  
Sometimes you open spectrum and you discover that it is centered on a frequency / band completely different from the one you were receiving before.
