### ISSUE TITLE
 SUPER FAST spectrum channel mode - freeze

### ISSUE THREAD

**Issue by grayker** [kamilsss655/uv-k5-firmware-custom#55]
When In Memory Channel mode press F+5 to enter SUPERFAST spectrum channel mode - QuanSheng UVK5(8) is frozen, every time after a few time. This trouble has happened with me  and some  my friends, whose try your firmwares. This  trouble  exists in all your firmwares. After the QuanSheng UVK5(8)  has frozen  need to turn off and turn on the QuanSheng UVK5(8) to make it work again. The QuanSheng UVK5(8) freezes every time you try

**Comment by kamilsss655** [comment]
@grayker It will be caused by a strong signal. The only way to fix this is to lower your gain settings in spectrum (while antenna is disconnected).

This issue is not software related.

@ErikS-web can you add some form of disclaimer or FAQ - lots of people bring up this subject.
