### ISSUE TITLE
[FEATURE] VFO mode, F + UP/DOWN  == move + / - 1 MHz

### ISSUE THREAD

**Issue by xes** [kamilsss655/uv-k5-firmware-custom#56]
Enhancement:
Many devices has the function where with function "F" selected, buttons UP/DOWN move vfo tuning frequency up or down of 1 Mhz.
Please could you add the same feature?

**Comment by zylka5** [comment]
Maybe instead of 1MHz steps, make it 100Hz which would be useful for quick tuning/netting during SSB transmissions.

**Comment by kamilsss655** [comment]
Considering the bin size constraints this will not be implemented.
