### ISSUE TITLE
Messenger Bug

### ISSUE THREAD

**Issue by GmrsKissimmee** [kamilsss655/uv-k5-firmware-custom#62]
It has been giving me some errors when sending short messages, being close or 2 meters away to test and the screen shows: unknown msg format. The text is also cut and symbols appear instead of what is written.
![IMG_20240111_132329](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/155043316/36ccc56b-c5d6-4302-be9e-344a5d96eae5)
![IMG_20240111_132049](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/155043316/bbdc82fc-d1d6-429b-9d7a-9d79c96b6ddc)
![IMG_20240111_141516](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/155043316/7c3046b8-6695-433d-b30b-a2ad5ce532e4)

**Comment by kamilsss655** [comment]
As discussed it works with:
* **no CTCSS code set**
* L power (if radios are close)
* 12.5k BW
