### ISSUE TITLE
Code decoding spectrum

### ISSUE THREAD

**Issue by GmrsKissimmee** [kamilsss655/uv-k5-firmware-custom#65]
Is it possible to do in the spectrum that when scanning and receiving a frequency, it deciphers the CTCSS or DCSS?

Regards

**Comment by kamilsss655** [comment]
Yes, it is on the roadmap, but unlikely to be implemented soon.

**Comment by kamilsss655** [comment]
Seems like the audio is muted during scan so this might not actually work.
