### ISSUE TITLE
AM airband rx has issue

### ISSUE THREAD

**Issue by sparky93a** [kamilsss655/uv-k5-firmware-custom#67]
as noted elsewhere, AM airband rx has issue
17.0 is fine.

but 17.1 up and including 19.1, the rx is choppy when signal strength is variable. agc tried off/slow/fast but still big steps? 

tested once home with sig gen on low tx levels and recreate issue very well.
 
also am air seems to default to 25k bandw not 12.5, but that could be just my settings. fyi.

thanks for your work :-) 73

**Comment by kamilsss655** [comment]
I guess it depends on a lot of variables.
I got reports from other users with reception videos showing improved reception in these versions.

Please try different gain settings in spectrum. Otherwise please upload a video showing your gain, agc settings and the mentioned 'has issue' phenomenon. :)
