### ISSUE TITLE
[BUG] messenger/fmradio: Can't unlock radio if auto lock is ON

### ISSUE THREAD

**Issue by T1MOXA** [kamilsss655/uv-k5-firmware-custom#73]
If radio gets auto-locked it's impossible to unlock until reboot.

**Comment by kamilsss655** [comment]
Same issue with FM radio.

**Comment by trlink** [comment]
Hi all,

it's solved in my fork...

kr

Christian

**Comment by kamilsss655** [comment]
fixed in 21.6
