### ISSUE TITLE
messenger: can't send messages in 19.4, in 19.3 worked fine

### ISSUE THREAD

**Issue by T1MOXA** [kamilsss655/uv-k5-firmware-custom#74]
When pressing menu button to send text, radio just beeps, whereas in the old version, a message was sent

**Comment by kamilsss655** [comment]
Cannot reproduce. Works fine.

Maybe it's your BW, power, conditions.

**Comment by T1MOXA** [comment]
The difference between two radios is:
CFW 19.3 and 19.4
models, uv k5 (k6) and uv 5r plus
Maybe some settings.

**Comment by T1MOXA** [comment]
Any idea how to fix this issue ?

**Comment by kamilsss655** [comment]
Since you haven't shared details on your settings I was not able to reproduce the issue.
Because of that I cannot help you further.

**Comment by T1MOXA** [comment]
> Since you haven't shared details on your settings I was not able to reproduce the issue. Because of that I cannot help you further.

II'd be happy to help with debugging.
I just don't know what could be the cause other than what I've already listed.

**Comment by T1MOXA** [comment]
Updated CFW to v.19.8, and problem persists.
I also checked setting through menu, side by side, and all settings was identical, even frequency is the same.
I don't know what else can cause the problem. May be different versions of hardware ?

**Comment by T1MOXA** [comment]
Looks like the problem was fixed in newer firmware!
