### ISSUE TITLE
[NO BEEP ON STARTUP WITH BEEP ON STARTUP ACTIVATED INTO THE MAKEFILE]

### ISSUE THREAD

**Issue by ElDiablo88** [kamilsss655/uv-k5-firmware-custom#76]
[NO BEEP ON STARTUP WITH BEEP ON STARTUP ACTIVATED INTO THE MAKEFILE]

**Comment by kamilsss655** [comment]
Why do you need beep on startup? Is there any issue this beep helps with?

**Comment by ElDiablo88** [comment]
_Oh ok I thought it was expected seeing the function to be enabled in the makefile..._

**Comment by kamilsss655** [comment]
No that's a fair point, I just wonder if you have some specific need for it.
Otherwise I'll just remove this option to avoid confusion.

**Comment by ElDiablo88** [comment]
No nned for it, i repeat i've seen the option into the makefile and i enabled but don't work and i thought was a bug. For me u can remove this. Good work!!
