### ISSUE TITLE
[FEATURE] Spectrum analyzer auto-switch (FM/AM/USB) on channel mode

### ISSUE THREAD

**Issue by KerseyPaul** [kamilsss655/uv-k5-firmware-custom#77]
Feature request: would it be possible for the spectrum analyzer (while operating in channel mode) to automatically switch between FM/AM/USB as per previously set in the channel/memory slot?

Thanks in advance.

**Comment by kamilsss655** [comment]
Hi @KerseyPaul I do have some enhancement planned that would address what you've mentioned and a couple of other things.

Not sure if it will work and if it will be implemented, but stay tuned! :)

**Comment by kamilsss655** [comment]
I do have that planned :)

**Comment by kamilsss655** [comment]
I was considering these changes, but based on bin size restraints and also the fact that dynamically changing rx params when we enter rx mode, will cause the rssi to change and cause glitchy squelch issues etc it is unlikely to be added.
