### ISSUE TITLE
[BUG] Spectrum in channel mode

### ISSUE THREAD

**Issue by PieeerB** [kamilsss655/uv-k5-firmware-custom#78]
I found a pattern when the spectrum freezes in channel mode. If we launch the spectrum from a channel with a bandwidth of 25k, then the spectrum freezes, if we launch the spectrum from a channel with a bandwidth of 12.5, then the spectrum works without failures

**Comment by kamilsss655** [comment]
You obviously didn't read the Wiki:
https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/80-%E2%80%90-Tips-&-Tricks-and-Known-Issues#what-if-spectrum-scan-freezes

**Comment by PieeerB** [comment]
I read this before, I just wrote to you that with a channel width of 12.5, the spectrum does not hang at all
