### ISSUE TITLE
[FEATURE] Last heard channel

### ISSUE THREAD

**Issue by fsclavo** [kamilsss655/uv-k5-firmware-custom#80]
I frequently monitor two different repeaters with the radio (dual watch mode), and I think it will be useful that the radio show in the screen some indication of the last received channel.
An example use case: if I'm not in front of the radio and I heard someone calling on a channel, if that station is not transmitting it is impossible to know in which channel the station was calling. Maybe a simple "LR" (last received) mark in the channel row could help in which channel TX to reply the call.
Thanks @kamilsss655 for this great firmware!

**Comment by fsclavo** [comment]
> Not the Author, but based on the example they gave, I think they'd want something that last longer. The DWR indicator only lasts for a few seconds, and its purpose is to indicate you can respond on that VFO.
> 
> A dedicated LR mark that stays on permanently (unless the other VFO receives something, of course) would certainly be nice, and I think that's what fsclavo meant. This would work in "dual RX, main TX" mode (DW) too, not just DWR.

That is exactly what I mean. Dual respond is useful, but it lasts just a few seconds so if you can't reach the radio in that seconds it is useless to identify which frequency was the station calling on.

**Comment by kamilsss655** [comment]
@fsclavo would making the dual respond marker stay longer resolve your issue?

**Comment by fsclavo** [comment]
Yes, at least it will be more useful!

**Comment by kamilsss655** [comment]
@fsclavo sorry but this would increase the DUAL WATCH hang time from 3.6 to 10 seconds, making radio deaf to other station for 10 seconds, which is opposite of what the user want with dual watch. Because of that it will not be implemented.

For your specific use case you can modify this line of code:
`const uint16_t    dual_watch_count_after_2_10ms    =  10000 / 10;`
to have it at 10 seconds.

**Comment by fsclavo** [comment]
I'll give it a try, thanks!

**Comment by fsclavo** [comment]
The problem I'm trying to solve is when you close to your radio but you can
hear it.
