### ISSUE TITLE
[FEATURE] Custom CHIRP driver

### ISSUE THREAD

**Issue by LordVertice** [kamilsss655/uv-k5-firmware-custom#83]
**Is your feature request related to a problem? Please describe.**
Many of the differences introduced by this FW aren't reflected when making changes through CHIRP. They might get saved properly, but adjusting these settings if difficult, especially in bulk.

Particularly notable are things like the new bandwidths, that one may need to edit in bulk for many memory channels at once, but other things like the new assignable buttons are missing from CHIRP as well.

**Describe the solution you'd like**
A custom CHIRP driver forked from egzumer's would do the trick. (that's probably much easier said than done)

**Describe alternatives you've considered**
egzumer's CHIRP driver still works for backups (I hope...) and some simple edits, and most of the incompatible features can be adjusted in the radio itself. A custom CHIRP driver isn't absolutely necessary, and simply leaving things as-is would be alright if it's too much work to get going and maintain.

That's all. Either way, thank you and everyone else involved for the firmware!

**Comment by kamilsss655** [comment]
I consider this but I am just a single developer working on this, so maintaining all would be hard.

Would you be interested in working on the CHIRP fork?

**Comment by kamilsss655** [comment]
@LordVertice I forked the CHIRP driver for you:
https://github.com/kamilsss655/uvk5-chirp-driver

Once you feel like contributing you can submit your PR's there.

**Comment by OE1MWW** [comment]
I receive a "Invalid or unsupported module file' of Chirp if I try to load this module above.

**Comment by 8cH9azbsFifZ** [comment]
Seems like there is a fix for current CHIRP and repo version :)

**Comment by tonurics** [comment]
The egzumer module is now part of the official Chirp-Next build and refuses to work with this firmware now.

Here's an edited version of the latest egzumer module with a check supporting this firmware: [uvk5_nunu.py.txt](https://github.com/kamilsss655/uv-k5-firmware-custom/files/14410050/uvk5_nunu.py.txt)

This firmware and egzumer are still similar enough that many settings are saved in the correct format. This module simply passes the firmware version check without any other changes. **Use at your own risk.**

I recommend reading from the radio first and limiting your edits to memory channels. However, I've noticed the bandwidth of some memory channels can sometimes be saved incorrectly. I can confirm settings like the Radio ID, DTMF contacts, welcome screen strings, etc. are saved correctly. But by editing the settings, things such as the saved function key actions are erased.

So far, these are all problems that can be fixable on the radio itself using the menus.

**Comment by kamilsss655** [comment]
The https://github.com/kamilsss655/uvk5-chirp-driver seems to be working just fine.

**Comment by nikant** [comment]
Hi and thank you for all your efforts! 
Just trying to understand if I am doing something wrong with latest CHIRP chirp-next-20240312-win64
and the module from your link 
Please check this video https://www.facebook.com/772359029/videos/7363625847047795/

**Comment by tonurics** [comment]
@nikant The steps you are doing in Chirp are correct.

Try using the updated module I shared above. [Rename the file to remove the ".txt" from the file extension.]

**Comment by OE1MWW** [comment]
@nikant if your firmware has a different name on start screen, change in the line 465 according your text.
Replace the 'NUNU' or the 'EGZUMER' with your firmware name.

 464   def k5_approve_firmware(cls, firmware):
 465       return (firmware.startswith('EGZUMER ') or firmware.startswith('NUNU '))

**Comment by tonurics** [comment]
@OE1MWW

Sounds like you're telling him to edit the "uvk5_nunu.py" module I shared; if so he won't need to make any changes.

The problem is that he was trying to use https://github.com/kamilsss655/uvk5-chirp-driver which is simply extending the *chirp_common.CloneModeRadio* class; which is unstable and changes with each version of Chirp. I read somewhere that the attributes were being parameterized in the latest version; which might be why the old module is breaking now. [The module I shared above uses the uvk5.UVK5RadioBase class instead.]

Note: The version I shared above is itself out of date. But should still work for now.

**Comment by OE1MWW** [comment]
@tonurics @nikant 
His (@nikant ) firmware starts with 'NKK 0.0.5nN  thefore his lines should be:

464 def k5_approve_firmware(cls, firmware):
465 return (firmware.startswith('EGZUMER ') or firmware.startswith('NKK '))

There is a space ' ' behind the 'NKK'. I have changed my fork accordingly to the name of my firmware.
I see no problems, even with the latest Chirp.

**Comment by kamilsss655** [comment]
Hey guys, thanks for the comments. I haven't noticed any issues yet, but if you had to make some changes to make it work you can submit a PR to https://github.com/kamilsss655/uvk5-chirp-driver

**Comment by tonurics** [comment]
@OE1MWW

Sorry, where is the information about his firmware version coming from? [The video he uploaded shows an _"Invalid or unsupported module file"_ error; not a _"Firmware X not supported"_ error. ]

If you need/want to make edits, bypass the firmware version check entirely using:
> **464** `def k5_approve_firmware(cls, firmware):`
> **465** `    return True`

**Comment by nikant** [comment]
> @nikant if your firmware has a different name on start screen, change in uvk5_nunu.py the line 465 according your text. Replace the 'NUNU' or the 'EGZUMER' with your firmware name.
> 
> 464 def k5_approve_firmware(cls, firmware): 465 return (firmware.startswith('EGZUMER ') or firmware.startswith('NUNU '))

Thank you all for the answers! 

No I wasn't trying the fork of kamilsss655 firmware.. I was just trying the module https://github.com/kamilsss655/uvk5-chirp-driver to verify if it works or not as @tonurics said

The reason was simply I got flamed on FB just by saying that kamilsss655 firmware (which I also forked because I like it) doesn't work with CHIRP **out of the box or by the driver in the link above**. 

Anyway.. again thank you all for your time
