### ISSUE TITLE
[BUG] BusyCL not functional

### ISSUE THREAD

**Issue by jan-Sanku** [kamilsss655/uv-k5-firmware-custom#84]
**Describe the bug**
I'm able to transmit while receiving, even with BusyCL set to ON (everything appears as if it was off).

With bad timing, this will prevent 2 senders (who expected BusyCL to work) from hearing each other, and will cause interference for any 3rd parties.

**To Reproduce**
1. Turn on BusyCL (either in VFO or MR mode)
2. If in MR mode, save the channel just in case
3. Receive something
4. Hold PTT

**Expected behavior**
"BUSY" (or something like that) should appear on screen, the transmission should not go out, and the radio should continue to receive as if the PTT button wasn't being held.

**Details:**
- Firmware version: v.19.6
- Bandwidth: 12.5
- Power: L
- RxAGC: FAST
- Gain settings (LNAs/LNA/PGA): default
- other: BusyCL ON

**Comment by yo-g1** [comment]
problem with adding channel name after channel save

**Comment by kamilsss655** [comment]
@LordVertice does the same bug occur with egzumer fw?

**Comment by kamilsss655** [comment]
Might make sense to delete that functionality, considering that radios have a hardware busy channel lock coming from the factory (lack of tantalum capacitor).

**Comment by kamilsss655** [comment]
Oh this function works as intended in `v.20.5` it displays `BUSY` and prevents TX.
