### ISSUE TITLE
Poprawka strojenia VFO

### ISSUE THREAD

**Issue by zylka5** [kamilsss655/uv-k5-firmware-custom#86]
Przydała by się poprawka strojenia z wykorzystywaniem długich przeciśnięć klawiszy w trybie vfo.
Taka jak ta:
https://github.com/egzumer/uv-k5-firmware-custom/commit/894157688717d1e7616c92a3482f9ad1731ddb2c

**Comment by kamilsss655** [comment]
Done in [release v.19.10](https://github.com/kamilsss655/uv-k5-firmware-custom/releases/tag/v.19.10)

**Comment by ErikS-web** [comment]
@zylka5.

Pse verify, Than this Issue can be closed bij you.
