### ISSUE TITLE
Spectrum channel mode normalization not working

### ISSUE THREAD

**Issue by KerseyPaul** [kamilsss655/uv-k5-firmware-custom#88]
(running the latest v.19.8)

When in the Spectrum Analyzer channel mode, **pressing FN2 makes no effect**. As per the F/W version .19.7 description text, it should "_flatten spectrum by bringing up all of the RSSI readings to the peak value, plus resolve the 'valley problem' with channels hiding behind other channels of higher noise floor_".

Also, to confirm its activation a **"N(0x)"** symbol should appear at the bottom of the screen - **which doesn't occur.**

Thanks in advance and congratulations once more for the outstanding job you're doing!

P.s.: channel attenuation and blacklisting functions are working normally.

**Comment by kamilsss655** [comment]
I suggest you read the release notes again.

sob., 20 sty 2024, 20:36 użytkownik KerseyPaul ***@***.***>
napisał:
