### ISSUE TITLE
[BUG] DWR not working as expected

### ISSUE THREAD

**Issue by fsclavo** [kamilsss655/uv-k5-firmware-custom#90]
As mentioned on Telegram, Dual Watch Respond isn't working as expected: even when secondary channel is on RX, if I press PTT the radio transmits on primary channel.

FW Version: v19.8

**Comment by kamilsss655** [comment]
Thanks @fsclavo.

Does the issue affect @egzumer fw as well?

**Comment by ErikS-web** [comment]
See Wiki

under [10 ‐ Radio operation](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/10-%E2%80%90-Radio-operation)

- The main channel is marked ► and with PTT active ►TX

_Read Main also as Primary..._

under [20 ‐ Menu](https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/20-%E2%80%90-Menu)

47. `RxMode` - sets how how the upper and lower frequency is used
   * MAIN ONLY - always transmits and listens on the main frequency (NO extra characters on screen)
   * DUAL RX RESPOND - listens to both frequencies, if signal is received on the secondary frequency it locks to it for a couple of seconds so you can respond to the call (**`DWR`** on screen)
   * CROSS BAND - always transmits on the MAIN/primary and listens on the secondary frequency (**`XB`** on screen)
   * MAIN TX DUAL RX - **always transmits on the primary**, listens to both (**`DW`** on screen)

**Comment by fsclavo** [comment]
> Does the issue affect @egzumer fw as well?

The last egzumer version I've used was v0.20, as far as I can remember DWR worked fine.

**Comment by kamilsss655** [comment]
Yup, this bug doesn't occur on latest egzumer.

**Comment by fsclavo** [comment]
Wow, that was fast! I could try in a few hours when I get home: will try v19.10 and if I found any problem, I'll let you know.
Thanks!

**Comment by ErikS-web** [comment]
@fsclavo: Any time to test ....and what is the result ?

Solution was....
![Knipsel](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/148579604/02a64fd7-156a-45af-afc1-4709dc78d925)

And it is included in[latest release v.19.10 ](https://github.com/kamilsss655/uv-k5-firmware-custom/releases/tag/v.19.10)

**Comment by fsclavo** [comment]
I've just updated my radio to v19.10 and DWR is working as expected.
Thanks!
