### ISSUE TITLE
[BUG] problem with adding channel name after channel save

### ISSUE THREAD

**Issue by yo-g1** [kamilsss655/uv-k5-firmware-custom#98]
**BEFORE YOU CREATE A BUG REPORT MAKE SURE YOU READ THIS**:
https://github.com/kamilsss655/uv-k5-firmware-custom/wiki/80-%E2%80%90-Tips-&-Tricks-and-Known-Issues

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Pictures/video**
If applicable, add pictures or video to help explain your problem.
To insert a picture (.jpg), you can simply drag it to this window.

**Details:**
- Firmware version:
- Bandwidth:
- Power: 
- RxAGC: 
- Gain settings (LNAs/LNA/PGA): 
- other:

**Additional context**

**Comment by ErikS-web** [comment]
And now, what is the BUG ?

PSe follow the instruction and make this a SMART issue !
