### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by lohtse** [kamilsss655/uv-k5-firmware-custom#99]
![image](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/48331155/8d017d16-124e-4e16-b5db-43c0f85f93c2)

seems to be an issue.

JUST downlowded the REPO so I know it is nothing to do with anything I did....   And every other repo I compile  etc for K5s compiles fine.

**Comment by kamilsss655** [comment]
You need to compile with Docker:
`make run`
